Repository 0NYE/FPS-frontend, pull requests merged in 2023-05, with the labels that each got.

#17 LoginModal UI 구현
  package-lock.json
  package.json
  src/App.tsx
  src/components/Button/Button.component.tsx
  src/components/Button/Button.styles.tsx
  src/components/LabeledInput/LabeledInput.component.tsx
  src/components/LabeledInput/LabeledInput.styles.tsx
  src/components/LoginForm/LoginForm.component.tsx
  src/components/LoginForm/LoginForm.style.tsx
  src/components/LoginModal/LoginModal.component.tsx
  src/components/LoginModal/LoginModal.styles.tsx
  src/components/LoginModal/Tab/Tab.component.tsx
  src/components/LoginModal/Tab/Tab.styles.tsx
  src/components/SignUpForm/SignUpForm.component.tsx
  src/components/SignUpForm/SignUpForm.styles.tsx
Labels: ✨ feat

#13 ProblemBlock 컴포넌트 구현
  src/assets/images/Fail.svg
  src/assets/images/css.svg
  src/assets/images/dislike.svg
  src/assets/images/dislike_activated.svg
  src/assets/images/html.svg
  src/assets/images/javascript.svg
  src/assets/images/like.svg
  src/assets/images/like_activated.svg
  src/assets/images/person.svg
  src/assets/images/star.svg
  src/assets/images/star_activated.svg
  src/assets/images/success.svg
  src/assets/images/successrate.svg
  src/assets/images/tags.svg
  src/components/ProblemBlock/ProblemBlock.component.tsx
  src/components/ProblemBlock/ProblemBlock.styles.tsx
Labels: ✨ feat

#21 로그인, 회원가입 구현
  src/atoms/user.ts
  src/components/LoginForm/LoginForm.component.tsx
  src/components/SignUpForm/SignUpForm.component.tsx
  src/constants/api.ts
  src/hooks/useInput.ts
Labels: ✨ feat

#9 CircleChart 컴포넌트 구현
  src/components/CircleChart/CircleChart.component.tsx
  src/components/CircleChart/CircleChart.styles.tsx
  src/components/CircleChart/CircleProgressBar.component.tsx
  src/style/theme.ts
Labels: ✨ feat

#23 PostBlock 컴포넌트 구현
  src/assets/images/RightChevron.svg
  src/assets/images/comment.svg
  src/assets/images/star_activated.svg
  src/components/PostBlock/PostBlock.component.tsx
  src/components/PostBlock/PostBlock.styles.tsx
Labels: ✨ feat

#25 CommentInput 컴포넌트 구현
  src/components/CommentInput/CommentInput.component.tsx
  src/components/CommentInput/CommentInput.styles.tsx
Labels: ✨ feat

#29 HistoryBlock 컴포넌트 구현
  src/components/HistoryBlock/HistoryBlock.component.tsx
  src/components/HistoryBlock/HistoryBlock.styles.tsx
Labels: ✨ feat

#31 FileSubmitButton컴포넌트 구현
  src/assets/images/File.svg
  src/assets/images/FileActivated.svg
  src/components/FileSubmissionButton/FileSubmissionButton.component.tsx
  src/components/FileSubmissionButton/FileSubmissionButton.styles.tsx
Labels: ✨ feat

#33 SubmissonBlock컴포넌트 구현
  src/components/SubmissionBlock/SubmissionBlock.component.tsx
  src/components/SubmissionBlock/SubmissionBlock.styles.tsx
Labels: ✨ feat

#34 문제 리스트 페이지 구현
  package-lock.json
  src/App.tsx
  src/components/ProblemBlock/ProblemBlock.component.tsx
  src/components/ProblemBlock/ProblemBlock.styles.tsx
  src/hooks/useFetch.ts
  src/pages/ProblemListPage/ProblemListPage.component.tsx
  src/pages/ProblemListPage/ProblemListPage.styles.tsx
  src/types/problem.ts
Labels: ✨ feat

#39 문제 업로드 페이지 구현
  src/App.tsx
  src/atoms/code.ts
  src/components/CodeResultFrame/CodeResultFrame.component.tsx
  src/components/CodeResultFrame/CodeResultFrame.styles.tsx
  src/components/Tag/Tag.component.tsx
  src/components/Tag/Tag.styles.tsx
  src/components/TwoVerticalSection/TwoVerticalSection.component.tsx
  src/components/TwoVerticalSection/TwoVerticalSection.styles.tsx
  src/hooks/useInput.ts
  src/hooks/useTextArea.ts
  src/pages/CreateProblemPage/CreateProblemPage.component.tsx
  src/pages/CreateProblemPage/CreateProblemPage.styles.tsx
  src/pages/CreateProblemPage/ProblemInputForm/ProblemInputForm.component.tsx
  src/pages/CreateProblemPage/ProblemInputForm/ProblemInputForm.styles.tsx
  src/utils/readTextFromFile.ts
Labels: ✨ feat

#41 문제 풀이 페이지 구현
  package-lock.json
  package.json
  src/App.tsx
  src/components/CodeResultFrame/CodeResultFrame.component.tsx
  src/components/ProblemPageHeader/ProblemPageHeader.component.tsx
  src/components/ProblemPageHeader/ProblemPageHeader.styles.tsx
  src/components/ProblemPageMenu/ProblemPageMenu.component.tsx
  src/components/ProblemPageMenu/ProblemPageMenu.styles.tsx
  src/components/ProgressBar/ProgressBar.components.tsx
  src/components/ProgressBar/ProgressBar.styles.tsx
  src/pages/ProblemListPage/ProblemListPage.component.tsx
  src/pages/ProblemPage/ProblemPage.component.tsx
  src/pages/ProblemPage/ProblemPage.styles.tsx
  src/pages/ProblemSolve/ProblemSolve.component.tsx
  src/pages/ProblemSolve/ProblemSolve.styles.tsx
  src/style/theme.ts
  src/types/problem.ts
  src/utils/code.ts
  src/utils/html2canvas.ts
Labels: ✨ feat

#43 문제 생성 기능 수정
  src/pages/CreateProblemPage/ProblemInputForm/ProblemInputForm.component.tsx
Labels: 🐛 bug, ⚒️ fix

#44 head 태그 보강
  index.html
  src/assets/images/aim.svg
Labels: ✨ feat

#45 로그인 모달 연결
  src/App.tsx
  src/atoms/modal.ts
  src/components/LoginForm/LoginForm.component.tsx
  src/components/LoginModal/LoginModal.component.tsx
  src/components/MainHeader/MainHeader.component.tsx
  src/components/MainHeader/MainHeader.styles.tsx
  src/components/ProblemPageHeader/ProblemPageHeader.component.tsx
  src/components/ProblemPageHeader/ProblemPageHeader.styles.tsx
Labels: ✨ feat

#46 Noto Sans Korean 폰트 적용
  index.html
  src/style/GlobalStyles.ts
Labels: ✨ feat

#49 문제 생성 페이지 개선
  package-lock.json
  package.json
  src/assets/images/add.svg
  src/atoms/problemCreate.ts
  src/components/CodeResultFrame/CodeResultFrame.component.tsx
  src/components/FileSubmissionButton/FileSubmissionButton.component.tsx
  src/components/MarkdownEditor/MarkdownEditor.component.tsx
  src/components/MarkdownEditor/MarkdownEditor.styles.tsx
  src/components/MarkdownViewer/MarkdownViewer.component.tsx
  src/components/MarkdownViewer/MarkdownViewer.styles.tsx
  src/components/ProblemSection/ProblemSection.components.tsx
  src/components/ProblemSection/ProblemSection.styles.tsx
  src/components/Tag/Tag.component.tsx
  src/components/Tag/Tag.styles.tsx
  src/components/Tag/TagInput.component.tsx
  src/components/Tag/TagInput.styled.tsx
  src/constants/codeResult.ts
  src/constants/markdown.ts
  src/pages/CreateProblemPage/CreateProblemPage.component.tsx
  src/pages/CreateProblemPage/ProblemInputForm/ProblemInputForm.component.tsx
  src/pages/CreateProblemPage/ProblemInputForm/ProblemInputForm.styles.tsx
  src/pages/ProblemSolve/ProblemSolve.component.tsx
  src/pages/ProblemSolve/ProblemSolve.styles.tsx
Labels: ✨ feat

#50 헤더 기능 및 디자인 변경
  src/App.tsx
  src/assets/images/aim-arrow.svg
  src/assets/images/chevron_left.svg
  src/assets/images/list.svg
  src/components/Checkbox/Checkbox.style.tsx
  src/components/Logo/Logo.component.tsx
  src/components/Logo/Logo.styles.tsx
  src/components/MainHeader/MainHeader.styles.tsx
  src/components/ProblemPageHeader/ProblemPageHeader.component.tsx
  src/components/ProblemPageHeader/ProblemPageHeader.styles.tsx
  src/pages/CreateProblemPage/CreateProblemPage.styles.tsx
  src/pages/ProblemListPage/ProblemListPage.styles.tsx
  src/pages/ProblemPage/ProblemPage.component.tsx
  src/pages/ProblemSolve/ProblemSolve.component.tsx
Labels: ✨ feat

#51 문제 리스트 페이지 개선
  src/atoms/problem.ts
  src/components/ProblemBlock/ProblemBlock.component.tsx
  src/components/ProblemBlock/ProblemBlock.styles.tsx
  src/components/SearchBar/SearchBar.component.tsx
  src/components/SearchBar/SearchBar.styles.tsx
  src/pages/ProblemListPage/ProblemListPage.component.tsx
  src/pages/ProblemListPage/ProblemListPage.styles.tsx
  src/types/problem.ts
  src/utils/debounce.ts
Labels: ✨ feat

#52 일부 페이지에서 뒤로가기가 작동하지 않는 현상 수정
  src/App.tsx
  src/components/MainHeader/MainHeader.component.tsx
  src/components/MainHeader/MainHeader.styles.tsx
  src/components/ProblemPageMenu/ProblemPageMenu.component.tsx
  src/components/ProblemPageMenu/ProblemPageMenu.styles.tsx
  src/pages/ProblemPage/ProblemPage.component.tsx
Labels: ⚒️ fix

#53 문제 페이지 개선
  package-lock.json
  package.json
  src/assets/images/replay.svg
  src/assets/images/shortcut.svg
  src/components/ProblemSection/ProblemSection.styles.tsx
  src/components/ProgressBar/ProgressBar.components.tsx
  src/components/ProgressBar/ProgressBar.styles.tsx
  src/constants/codeResult.ts
  src/pages/ProblemSolve/ProblemSolve.component.tsx
  src/pages/ProblemSolve/ProblemSolve.styles.tsx
Labels: ⚒️ fix, ✨ feat

#54 문제 답 제출 구현
  src/pages/ProblemSolve/ProblemSolve.component.tsx
Labels: ✨ feat

#55 로그인 오류 해결
  src/components/LoginForm/LoginForm.component.tsx
  src/components/SignUpForm/SignUpForm.component.tsx
Labels: ⚒️ fix

#56 제출 결과 확인 기능 구현
  package-lock.json
  package.json
  src/components/LanguageSyntaxHighlighter/LanguageSyntaxHighlighter.component.tsx
  src/components/LanguageSyntaxHighlighter/LanguageSyntaxHighlighter.styles.tsx
  src/components/ProblemPageMenu/ProblemPageMenu.component.tsx
  src/components/SubmissionBlock/SubmissionBlock.component.tsx
  src/components/SubmissionBlock/SubmissionBlock.styles.tsx
  src/components/SubmissionBlockList/SubmissionBlockList.component.tsx
  src/components/SubmissionSummary/SubmissionSummary.component.tsx
  src/components/SubmissionSummary/SubmissionSummary.styles.tsx
  src/pages/ProblemPage/ProblemPage.component.tsx
  src/pages/ProblemSubmissions/ProblemSubmissions.components.tsx
  src/types/lighthouse.ts
  src/types/problem.ts
  src/utils/date.ts
  src/utils/lighthouse.ts
  src/utils/string.ts
Labels: ✨ feat

#57 UI 디테일 다듬기 및 오류 수정
  src/atoms/user.ts
  src/components/Avatar/Avatar.styles.tsx
  src/components/CodeResultFrame/CodeResultFrame.component.tsx
  src/components/LoginForm/LoginForm.component.tsx
  src/components/MainHeader/MainHeader.component.tsx
  src/components/ProblemPageHeader/ProblemPageHeader.component.tsx
  src/components/SubmissionBlockList/SubmissionBlockList.component.tsx
  src/components/SubmissionBlockList/SubmissionBlockList.styles.tsx
  src/components/SubmissionSummary/SubmissionSummary.component.tsx
  src/components/SubmissionSummary/SubmissionSummary.styles.tsx
  src/pages/ProblemSolve/ProblemSolve.component.tsx
  src/pages/ProblemSubmissions/ProblemSubmissions.components.tsx
  src/style/GlobalStyles.ts
  src/types/problem.ts
Labels: ⚒️ fix, ✨ feat
